export * from './lib/date'
export { default as uniqueCombinations } from './lib/uniqueCombinations'
export { default as shuffleArray } from './lib/shuffleArray'
export { default as getDelta } from './lib/rating-formula'
export { arrayToObject } from './lib/array-to-object'
export { default as upperFirstLetter } from './lib/upper-first-letter'
export { default as mapToArray } from './lib/map-to-array'
export { default as maxInCollection } from './lib/max-in-collection'
export { default as avgOfSet } from './lib/avg-of-set'