export {default as StatsPage} from './stats/StatsPage'
export {default as GameProcessPage} from './game-process/GameProcessPage'
export {default as UsersPage} from './users/UsersPage'
export {default as TourPage} from './tour/TourPage'
export {default as SequenceGeneratorPage} from './sequence-generator/SequenceGeneratorPage'